# NumPy

[NumPy](https://numpy.org/) is the fundamental package for scientific computing with Python.

Warum NumPy? 
- Python-Listen sind flexibel, aber langsam bei vielen numerischen Operationen.
- NumPy bietet den ndarray-Datentyp: ein schnelles, speichereffizientes Array-Objekt.
- Viele mathematische Operationen werden in C implementiert, was NumPy extrem performant macht.
- Arrays können mehrdimensional sein (z. B. Vektoren, Matrizen, Tensoren).


## Grundlagen

In [16]:
import numpy as np

# Array erstellen aus Python-Liste
a = np.array([1, 2, 3, 4, 5])
print("Array      :", a)
print("Datentyp   :", a.dtype)
print("Dimensionen:", a.ndim)
print("Grösse     :", a.size)
print("Form       :", a.shape)


Array: [1 2 3 4 5]
Datentyp: int64
Dimensionen: 1
Grösse 5
Form: (5,)


## Arrays erzeugen

In [21]:
print("Array mit Nullen  :", np.zeros((2, 3)))
print("Array mit Einsen  :", np.ones((3, 3)))
print("Array von 0 bis 9 :", np.arange(10))
print("Array 10x 0 bis 1 :", np.linspace(0, 1, 10))


Array mit Nullen  : [[0. 0. 0.]
 [0. 0. 0.]]
Array mit Einsen  : [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Array von 0 bis 9 : [0 1 2 3 4 5 6 7 8 9]
Array 10x 0 bis 1 : [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Mathematische Operationen

Mit Numpy können mathematische Operationen per Element ausgeführt werden:

In [22]:
a = np.array([1, 2, 3, 4, 5])
print("a + 10 :", a + 10)
print("a * 2  :", a * 2)
print("a ** 2 :", a ** 2)
print("Sinus  :", np.sin(a))


a + 10 : [11 12 13 14 15]
a * 2  : [ 2  4  6  8 10]
a ** 2 : [ 1  4  9 16 25]
Sinus  : [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [26]:
# Operationen mit Numpy Arrays erfolgen per Element:

a = np.array([20,30,40,50] )
b = np.array([10,12,20,35] )
c = a-b

print(a)
print(b)
print(c)

[20 30 40 50]
[10 12 20 35]
[10 18 20 15]


## Mehrdimensonale Arrays (Matrizen)

In [4]:
m = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", m)

# Transponieren
print("Transponiert:\n", m.T)

# Matrixmultiplikation
n = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("Matrixprodukt:\n", m.dot(n))


Matrix:
 [[1 2 3]
 [4 5 6]]
Transponiert:
 [[1 4]
 [2 5]
 [3 6]]
Matrixprodukt:
 [[1 2 3]
 [4 5 6]]


## Slicing

Analog der Python Listen können auch mit Numpy Array Selektionen von Elementen mit Hilfe von Slicing erfolgen.

In [31]:
x = np.array( [[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Matrix:\n", x)


print("Erste Zeile   :",x[0, :]) # first line
print("Erste Spalte  :",x[:, 0]) # first column
print("Erstes Element:",x[0, 0]) # first element of first column

print("Erste 2 Elemente der 2ten Spalte:", x[0:2,1]) # first 2 elements of 2nd column

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Erste Zeile   : [1 2 3]
Erste Spalte  : [1 4 7]
Erstes Element: 1
Erste 2 Elemente der 2ten Spalte: [2 5]


## Statistiken

In [27]:
x = np.random.randint(0, 100, size=10)
print("Array             :", x)
print("Mittelwert        :", np.mean(x))
print("Standardabweichung:", np.std(x))
print("Maximum           :", np.max(x))
print("Index des Maximums:", np.argmax(x))


Array             : [62  9 99 60 63 36 89 78 17 39]
Mittelwert        : 55.2
Standardabweichung: 28.17019701741541
Maximum           : 99
Index des Maximums: 2


# Aufgaben

## Calculations

Führen sie folgenden Aufgaben aus:

**Berechnungen:**
- Erstellen Sie die folgenden drei Numpy Arrays.
  - a = [20,30,40,50]
  - b = [10,15,10,75]
  - c = [17,12,-3,52]
- Berechnen Sie elementweise:
  - x = a - b
  - y = x + c
- Geben Sie die Resultate auf der Konsole aus.

**6er Reihe:**
- Erstellen Sie einen Numpy Array mit den Werten der 6er Reihe (verwenden Sie dazu die Range Funktion).
- Berechnen Sie folgende Werte und geben Sie diese auf der Konsole aus:
  - Minimum
  - Maximum
  - Mittelwert
  - Standardabweichung

**Lottozahlen:**
- Erstellen Sie mit der Numpy Funktion ranom.randint() sechs Zufallszahlen im Bereich von 1 bis 45.
- Jede Zufallszahl darf nur einmal vorkommen in der generierten Liste.
- Geben Sie die Zahlen auf der Konsole aus.

Beispiel Ausgabe:
```
Berechnungen:
x: [ 10  15  30 -25]
y: [27 27 27 27]

6er Reihe: [ 6 12 18 24 30 36 42 48 54 60]
Minimum: 6
Maximum: 60
Mittelwert: 33.0
Standardabweichung: 17.233687939614086

Lottozahlen:
{34, 3, 8, 43, 18, 25}
```


In [6]:
import numpy as np

# Part I - Berechnungen
a = np.array([20,30,40,50])
b = np.array([10,15,10,75])
c = np.array([17,12,-3,52])

x = a - b
y = x + c

print("Berechnungen:")
print("x:", x)
print("y:", y)


# Part II - 6er Reihen
r6 = np.array(range(6,66,6))
print("\n6er Reihe:", r6)

print("Minimum:",np.min(r6))
print("Maximum:",np.max(r6))
print("Mittelwert:",np.mean(r6))
print("Standardabweichung:",np.std(r6))


# Part III - Lottozahlen
print("\nLottozahlen:")
lotto = set()

while len(lotto) < 6:
    n = np.random.randint(1, 46)
    lotto.add(n)

print(lotto)

Berechnungen:
x: [ 10  15  30 -25]
y: [27 27 27 27]

6er Reihe: [ 6 12 18 24 30 36 42 48 54 60]
Minimum: 6
Maximum: 60
Mittelwert: 33.0
Standardabweichung: 17.233687939614086

Lottozahlen:
{35, 3, 36, 6, 15, 28}


## Performance

In diesem Beispiel wollen wir die Performance von Numpy Operationen mit Standard Python vergleichen. Dazu lösen wir folgende Aufabe:

1. Erzeuge eine Liste mit 5 Millionen Einträgen, wobei jeder Eintrag ein Tupel aus 5 Zufallszahlen (0–100) ist.
2. Summiere die 5 Spalten einmal mit reinem Python (verschachtelte Schleifen).
3. Summiere die 5 Spalten ein zweites Mal mit NumPy (np.sum).
4. Miss und vergleiche die Ausführungszeit beider Varianten.
5. Überlege: Warum ist NumPy deutlich schneller?

Tipps:
- Verwende das Modul time, um die Laufzeit mit time.time() zu messen.
- Erstelle die Zufallsdaten mit einer List-Comprehension und random.randint().
- Zum Summieren in Python kannst du eine Liste mit 5 Nullen anlegen und in einer Schleife Zeile für Zeile addieren.
- In NumPy kannst du die Liste einfach in ein np.array umwandeln und mit np.sum(arr, axis=0) die Spalten aufsummieren.
- Denke daran, die Ergebnisse (Summen und Zeit in Sekunden) am Ende auszugeben.

In [5]:
import time
import random
import numpy as np

# 
# Testdaten (5 Millionen Einträge mit je 5 Zufallszahlen zwischen 0..100)
#
n = 5_000_000
data = [(random.randint(0, 100),
         random.randint(0, 100),
         random.randint(0, 100),
         random.randint(0, 100),
         random.randint(0, 100)) for _ in range(n)]

data_np = np.array(data)   # Umwandeln in NumPy Array


# 
# Summe mit Python bilden und Zeit messen
# 
start = time.time()

sums_py = [0, 0, 0, 0, 0]
for row in data:
    for i in range(5):
        sums_py[i] += row[i]

end = time.time()
time_py = round(end - start, 4)


# 
# Summe mit NumPy bilden und Zeit messen
# 
start = time.time()

sums_np = np.sum(data_np, axis=0)

end = time.time()
time_np = round(end - start, 4)
time_np_percent = round(100 * time_np / time_py, 2)

#
# Ergebnisse
#
print(f"Summen mit Python: {sums_py}")
print(f"Zeit mit Python  : {time_py} (100.00%)")

print(f"Summen mit Numpy : {sums_np}")
print(f"Zeit mit Numpy   : {time_np} ({time_np_percent}%)")

Summen mit Python: [249999206, 249953711, 249994128, 250114718, 249903739]
Zeit mit Python  : 2.8904 (100.00%)
Summen mit Numpy : [249999206 249953711 249994128 250114718 249903739]
Zeit mit Numpy   : 0.0399 (1.38%)
